name: 'Podcast directory action'
description: 'Github Action to help maintaining a directory of podcasts'
inputs:
  podcast-yaml-directory:
    description: 'directory where to store .yaml podcast description files'
    required: true
    default: 'podcasts'
  repo_token:
    description: 'Github personal access token to generate the podcast file'
    required: true
outputs:
  title:
    description: 'The title of the podcast'
  filename:
    description: 'The podcast yaml description file'
  rss:
    description: 'The podcast rss feed URL'
runs:
  using: 'node12'
  main: 'dist/index.js'
